### ISSUE TITLE
Search box issue

### ISSUE THREAD

**Issue by BrunoCaxito** [TheHerobrine/DarkerNodes#117]
The search box results overlaps and bugs when searching for a variable type, becoming unreadable. Hovering with the mouse, partially fixes the problem.

Searching for a variable type:
![Captura de tela 2021-01-24 190158](https://user-images.githubusercontent.com/8711629/105644852-a8700e80-5e76-11eb-9111-e9f5d947e932.png)

Mouse hovers:
![Captura de tela 2021-01-24 190410](https://user-images.githubusercontent.com/8711629/105644890-f553e500-5e76-11eb-8091-38e84b5316f5.png)

I'm using the latest update, not sure when this started.

**Comment by TheHerobrine** [comment]
Hum, this is a known bug, it should have been fixed with 2.4 and I was not sure if it could reappear with updates.
I'll try to create an autofix on the next update.

To solve this, try this: https://github.com/TheHerobrine/DarkerNodes/wiki/FAQ#some-elements-are-invisible--search-box-are-glitchy-or-unreadable

**Comment by BrunoCaxito** [comment]
> Hum, this is a known bug, it should have been fixed with 2.4 and I was not sure if it could reappear with updates.
> I'll try to create an autofix on the next update.
> 
> To solve this, try this: https://github.com/TheHerobrine/DarkerNodes/wiki/FAQ#some-elements-are-invisible--search-box-are-glitchy-or-unreadable

Yes, this solves the problem. Thank-you.
