### ISSUE TITLE
Missing background color inside text area in curve editor

### ISSUE THREAD

**Issue by Xpert0** [TheHerobrine/DarkerNodes#140]
Steps to reproduce: 

1. Enable plugin
2. Set theme to Dark
3. Make a curve
4. Open curve editor
5. Bug as follows

![image](https://user-images.githubusercontent.com/32800008/111775278-d5f29a80-88b0-11eb-81e3-9ffee3a01650.png)

**Comment by TheHerobrine** [comment]
Yes, it's because the background is already dark (the same color of text background).

You can add a border in the settings here:
![image](https://user-images.githubusercontent.com/4563971/111775795-7ea0fa00-88b1-11eb-984c-0b27f158b025.png)

Result:
![image](https://user-images.githubusercontent.com/4563971/111775850-911b3380-88b1-11eb-963a-9cc509295d9a.png)
or
![image](https://user-images.githubusercontent.com/4563971/111775883-9bd5c880-88b1-11eb-8736-e13a7c4f1471.png)

**Comment by Xpert0** [comment]
Thanks, I didn't notice that option.
Would it be possible to change the border thickness?

**Comment by TheHerobrine** [comment]
Hum, yes! You'd like 2px for example?

**Comment by Xpert0** [comment]
Sounds good! Maybe a drop list of options or an input field would give more control to the user but idk if that's viable

**Comment by TheHerobrine** [comment]
I think, I'll go with a text field with int from 0 to 5 🤔

**Comment by Xpert0** [comment]
That's great, thanks
